ALTER TABLE research ADD COLUMN steps TEXT NOT NULL DEFAULT '[]';
ALTER TABLE research ADD COLUMN sources TEXT NOT NULL DEFAULT '[]';
ALTER TABLE research ADD COLUMN tokens INTEGER NOT NULL DEFAULT 0;
